# Build Template - Reusable Docker Image Build
# Learn: Image caching, multi-platform builds, optimization

.build_template:
  stage: build
  image: docker:24-git
  services:
    - docker:24-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - rm -rf invoiceninja
    - git submodule update --init --recursive --depth 20
    - echo "$GCP_SERVICE_KEY" > /tmp/gcp-key.json
    - cat /tmp/gcp-key.json | docker login -u _json_key --password-stdin https://${GCP_REGION}-docker.pkg.dev
    - rm /tmp/gcp-key.json
  script:
    - |
      docker build \
        --cache-from ${IMAGE_NAME}:latest \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --tag ${IMAGE_NAME}:${CI_COMMIT_SHA} \
        --tag ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} \
        --tag ${IMAGE_NAME}:latest \
        --file ${DOCKERFILE_PATH} \
        .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
    - docker push ${IMAGE_NAME}:latest
  after_script:
    - docker logout https://${GCP_REGION}-docker.pkg.dev
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# Web App Build Job
build:web:
  extends: .build_template
  variables:
    IMAGE_NAME: "${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/invoiceninja/web"
    DOCKERFILE_PATH: "docker/web/Dockerfile"
  artifacts:
    reports:
      dotenv: build-web.env
    expire_in: 1 day
  script:
    - |
      docker build \
        --cache-from ${IMAGE_NAME}:latest \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --tag ${IMAGE_NAME}:${CI_COMMIT_SHA} \
        --tag ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} \
        --tag ${IMAGE_NAME}:latest \
        --file ${DOCKERFILE_PATH} \
        .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA} || exit 1
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} || exit 1
    - docker push ${IMAGE_NAME}:latest || exit 1
    - echo "WEB_IMAGE=${IMAGE_NAME}:${CI_COMMIT_SHA}" > build-web.env
    - echo "WEB_IMAGE_TAG=${CI_COMMIT_SHA}" >> build-web.env

# Worker Build Job
build:worker:
  extends: .build_template
  variables:
    IMAGE_NAME: "${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/invoiceninja/worker"
    DOCKERFILE_PATH: "docker/worker/Dockerfile"
  artifacts:
    reports:
      dotenv: build-worker.env
    expire_in: 1 day
  script:
    - |
      docker build \
        --cache-from ${IMAGE_NAME}:latest \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --tag ${IMAGE_NAME}:${CI_COMMIT_SHA} \
        --tag ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} \
        --tag ${IMAGE_NAME}:latest \
        --file ${DOCKERFILE_PATH} \
        .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA} || exit 1
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} || exit 1
    - docker push ${IMAGE_NAME}:latest || exit 1
    - echo "WORKER_IMAGE=${IMAGE_NAME}:${CI_COMMIT_SHA}" > build-worker.env
    - echo "WORKER_IMAGE_TAG=${CI_COMMIT_SHA}" >> build-worker.env

# Multi-Architecture Build (Advanced)
build:multi-arch:
  extends: .build_template
  only:
    - tags
  script:
    # Set up QEMU for multi-arch builds
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    # Build for AMD64 and ARM64
    - |
      docker buildx create --use --name multiarch || true
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --cache-from ${IMAGE_NAME}:latest \
        --tag ${IMAGE_NAME}:${CI_COMMIT_TAG} \
        --tag ${IMAGE_NAME}:latest \
        --file ${DOCKERFILE_PATH} \
        --push \
        .
